name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != '${{ github.repository }}'
    runs-on: windows-2022
    strategy:
      matrix:
        os: [windows-2022]
    env:
      BUILD_TYPE: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Build
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} "-DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install" -B build
        cmake --build build
    - name: Install to temp dir
      run: cmake --install build --config ${{ env.BUILD_TYPE }}

    - name: Upload generic artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: notepad4
        path: ${{ github.workspace }}/install/bin/

    - name: zip the result
      working-directory: ${{ github.workspace }}/install/bin/
      run: 7z a notepad4.zip notepad4.exe

    - name: upload Release
      uses: softprops/action-gh-release@master
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/install/bin/notepad4.zip
